- docker/Dockerfile
- poetry.lock
- pyproject.toml
Update TOML to align package to be named CTMS instead of ctms-api, which also has poetry to look at CTMS directory instead of using the packages section of the toml to determine where to look.
Not a necessary change, but just came up per the issue.
> Issue #47, if desired this PR addresses this issue

- .github/workflows/build-image.yaml
- README.md
- guides/deployment_guide.md
main will add stg- to tags
prod will use releases, but nothing in this pr helps make that real, just documented for the future
both of these can then be matched with regex in the helm release
> Adding a staging tag to the commits on main when docker builds them

- ctms/app.py
- ctms/crud.py
- ctms/sample_data.py
- ctms/schemas/__init__.py
- ctms/schemas/addons.py
- ctms/schemas/base.py
- ctms/schemas/contact.py
- ctms/schemas/email.py
- ctms/schemas/fxa.py
- ctms/schemas/newsletter.py
- ctms/schemas/vpn.py
- tests/unit/conftest.py
- tests/unit/test_api.py
- Add 409 to responses for post. Fixes #75
- Make all schemas comparable. Fixes #77
- Return redirect from POST
- Check writes with more samples
- Improve schema model comparisons
- Don't write default models to db
I'm not 100% sure about any of this but I wanted to get this up for review before too long. Please feel free to tell me to change anything at all! It should be in_roughly_ reviewable commits.
> post endpoint pt2

- ctms/app.py
This groups it with the other public APIs in the interactive docs.
> Add POST /ctms to public API group

- ctms/schemas/email.py
_Describe the big picture of your changes here..._
> Make basket_token optional. Fixes #54

- .pre-commit-config.yaml
- ctms/app.py
- ctms/auth.py
- ctms/bin/client_credentials.py
- ctms/crud.py
- ctms/database.py
- ctms/schemas/addons.py
- ctms/schemas/contact.py
- ctms/schemas/email.py
- ctms/schemas/fxa.py
- ctms/schemas/newsletter.py
- ctms/schemas/vpn.py
- ctms/schemas/web.py
- poetry.lock
- pyproject.toml
- scripts/lint.sh
- tests/unit/conftest.py
- tests/unit/test_api.py
- tests/unit/test_auth.py
This pretty much just turns on pylint which theoretically was already here. I've done a best-effort pass to fix or disable everything. It should be reviewable revision-by-revision! Let me know if you disagree with anything in particular, etc
> Enable Pylint

- ctms/schemas/email.py
- tests/unit/test_api.py
_Describe the big picture of your changes here..._
> Allow missing in addition to None for email_id

- .github/workflows/build-image.yaml
- guides/deployment_guide.md
- guides/git_strategy.md
Changing tagging to -
be {shortsha} on all commits that don't match the other rules
be "stg-{shortsha}" for commits merged to main.
be "v{semver}" (ex v.0.0.1) for production deploys. (this should work for releases cut and annotated tags pushed via command line)
> Working to get tagging correct for all builds

- ctms/bin/load_sample_csv.py
- ctms/ingest.py
- ctms/models.py
- ctms/schemas/__init__.py
- ctms/schemas/addons.py
- ctms/schemas/email.py
- ctms/schemas/fxa.py
- ctms/schemas/newsletter.py
- ctms/schemas/vpn.py
- migrations/versions/20210330_8019ffa1614e_update_fields_from_sample_data_learnings.py
- pyproject.toml
- tests/unit/test_api.py
This works afaict. Next I want to add tests and add a script for importing from BQ directly. I want to land this before I do the rest of it to unblock other changes to models.
> Add first half of data ingestion

- ctms/bin/load_sample_csv.py
- ctms/ingest.py
- tests/data/good_csvs/CTMS_SAMPLE_contact_to_amo.csv
- tests/data/good_csvs/CTMS_SAMPLE_contact_to_email.csv
- tests/data/good_csvs/CTMS_SAMPLE_contact_to_fxa.csv
- tests/data/good_csvs/CTMS_SAMPLE_contact_to_newsletter.csv
- tests/data/good_csvs/CTMS_SAMPLE_contact_to_vpn_waitlist.csv
- tests/data/good_csvs/CTMS_SAMPLE_email_ids.csv
- tests/data/good_csvs_no_amo/CTMS_SAMPLE_contact_to_amo.csv
- tests/data/good_csvs_no_amo/CTMS_SAMPLE_contact_to_email.csv
- tests/data/good_csvs_no_amo/CTMS_SAMPLE_contact_to_fxa.csv
- tests/data/good_csvs_no_amo/CTMS_SAMPLE_contact_to_newsletter.csv
- tests/data/good_csvs_no_amo/CTMS_SAMPLE_contact_to_vpn_waitlist.csv
- tests/data/good_csvs_no_amo/CTMS_SAMPLE_email_ids.csv
- tests/unit/conftest.py
- tests/unit/test_bin_client_credentials.py
- tests/unit/test_bin_load_sample_csv.py
- tests/unit/test_ingest.py
This should cover (maybe not at a perfect level) much of the ingestion code in tests. It also changes how the ingestion uses the db such that all of the ingestion happens with sqlalchemy core and inside a single transaction. This speeds things up significantly
> Test and improve ingestion

- ctms/bin/load_sample_csv.py
- ctms/bin/sync_bq_tables.py
- ctms/ingest.py
- poetry.lock
- pyproject.toml
- First cut at BQ to CTMS import
- Add reporting to importer
- Handle misformed data a bit more niceely
There's still more to do to have this "productionized" in TODOs in the code. If we like where this is now, we can change those into issues for followup.
> Bigquery import works I think?

- ctms/app.py
- pyproject.toml
_Describe the big picture of your changes here..._
> Prepare to cut new release

- ctms/app.py
- ctms/schemas/contact.py
- tests/unit/test_api.py
> Updating api to allow blank strs for query params, updating response to include 'after', updating tests

- scripts/importers/copy_to_db.sh
- scripts/importers/finish.sql
- scripts/importers/setup.sql
Just for posterity's sake. Hopefully we won't need these soon.
> Store import script final state

- scripts/importers/finish.sql
Couple more fixes just to store for later
> Actually finish the import scripts

- docker/Dockerfile
- docker/gunicorn_conf.py
- poetry.lock
- pyproject.toml
For issue #141, use gunicorn with a uvicorn worker rather than uvicorn directly.
Local testing:
* Change ``docker-compose.yml`` to ``target: production``
* Run ``make build start``
* Look for the debug statement and multiple worker startup
> Use gunicorn in production target

- docker-compose.yaml
- pyproject.toml
In preparation for tagging as ``v0.7.0``:
* Add @imbstack to authors list, alpha sort
* Bump versions from 0.6.0 to 0.7.0
> Bump version to 0.7.0

- docker-compose.yaml
I used this to test PR #162, but it was not supposed to be committed.
> Use development build in development

- ctms/acoustic_sync.py
- ctms/config.py
This is roughly what you'll need to fit the query into. I thought about doing fancy stuff with timeouts here but I think instead we just be careful with the query and whatever is writing to acoustic to set appropriate timeouts there.
> Add basics of acoustic sync background job

- ctms/app.py
- ctms/crud.py
- tests/unit/test_api.py
- tests/unit/test_api_patch.py
This rebases and continue's @bsieber-mozilla's work on PR #135 to fix issue #105.
> Return contact data rather than 303 See Other

- .github/workflows/sphinx-pages.yaml
Used for documentation to be auto-generated:
> Removal of old branching name

- ctms/app.py
- pyproject.toml
Bumping version in `app.py` and `pyproject.toml` 
- 0.7.2 -> 0.8.0
> Version bump: 0.8.0

- ctms/bin/acoustic_sync.py
- ctms/config.py
- ctms/crud.py
- ctms/sync.py
Introduce env var CTMS_ACOUSTIC_BATCH_LIMIT default to 20.
Commit after each record is processed
> Hf batch limit and commit more

- ctms/acoustic_service.py
- ctms/background_metrics.py
- ctms/bin/acoustic_sync.py
- ctms/config.py
- ctms/crud.py
- ctms/sync.py
An initial attempt to tackle: https://github.com/mozilla-it/ctms-api/issues/125
> Adding Background Metrics

- ctms/acoustic_service.py
- tests/unit/test_acoustic_service.py
Relevant:
https://docs.google.com/document/d/10UPt9kSE0ynoBK-Tv5JOufkGdMwMogdmAbEoLc_apkk/edit
> Adding conversion into C->A backend sync for fxa_created_date

- ctms/app.py
- pyproject.toml
Hold on merging until further testing at 1pm pt meeting.
> Version bump: 1.0.1

- ctms/app.py
- tests/unit/test_api_stripe.py
This PR is looking to address issue #354 and uses the proposed solution by @jwhitlock
> Resolve when receiving None value

- ctms/app.py
- pyproject.toml
_Drafting up a version bump here_
> Version bump: 1.1.4

- ctms/acoustic_service.py
- tests/unit/test_acoustic_service.py
Following [gdoc](https://docs.google.com/document/d/1i2TsSFtTe1BdLFlgg90Vz8lBdtzIw2U5OSlr65-SR7o/edit) to add new newsletter
> Adding new newsletter.

- ctms/acoustic_service.py
Minor change; removing "sub" from key.
> Newsletter mapping update.

- ctms/app.py
- pyproject.toml
> Version Bump to new minor version

- .github/CODEOWNERS
Add @leplatrem to reviewer list
> Add leplatrem to Reviewer List

- ctms/app.py
- pyproject.toml
[Release in draft state.](https://github.com/mozilla-it/ctms-api/releases)
> (Tag) Version 1.4.0: New functionality for ingestion of relay_waitlist from API to Acoustic.

- ctms/config.py
- ctms/database.py
- docs/configuration.md
- poetry.lock
- pyproject.toml
Looking to resolve: 
https://mozilla-hub.atlassian.net/jira/software/c/projects/CTMS/boards/364
https://sentry.prod.mozaws.net/operations/ctms-stage/issues/15860536/?query=is%3Aunresolved
https://sentry.prod.mozaws.net/operations/ctms-stage/issues/19094618/?query=is%3Aunresolved
Slack thread with some additional details:
https://mozilla.slack.com/archives/G01M9NUSUG1/p1648750262524159
> Updates to Pre-commit and DB changes 

- ctms/config.py
- poetry.lock
- pyproject.toml
Modifying deps to reflect this comment: https://github.com/tiangolo/fastapi/issues/4041#issuecomment-1057879412
> Updating FastAPI and Starlette, modifying db create_engine EV's

- ctms/crud.py
- tests/unit/test_ingest_stripe.py
Once again removing the "of" param; now that there are DB-side changes. Trying to unravel this issue 😮‍💨
> Trying to unravel the ongoing db issues

- ctms/acoustic_service.py
- tests/unit/test_acoustic_service.py
Adds an entry to `MAIN_TABLE_SUBSCR_FLAGS` for the Security and Privacy Products newsletter ([CTMS-133](https://mozilla-hub.atlassian.net/browse/CTMS-133))
> [CTMS-133] Add security and privacy products newsletter

- docker/Dockerfile
Update Python base image to pick up the latest version of the openssl libraries.
https://mozilla-hub.atlassian.net/browse/SE-3097
> Update Python base image

- ctms/log.py
- poetry.lock
- pyproject.toml
FastAPI:   0.74.1 -> 0.79.0
Starlette: 0.17.1 -> 0.19.1
> Upgrade FastAPI and Starlette

- ctms/bin/flatten_subscriptions_from_firestore_export.py
> Migrating GIST from https://gist.github.com/bsieber-mozilla/314636a777a309ef4d305578a6d19fcc into repo

- ctms/app.py
- pyproject.toml
_Reverting until ready for release_
> Revert version bump

- .github/workflows/build-image.yaml
Allow deploys to staging with [workflow dispatches](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)
> Allow manually triggering deploys to stage

- tests/unit/test_acoustic_service.py
- tests/unit/test_sync.py
> Fix #457: Rework query assertions

- ctms/app.py
- ctms/crud.py
- tests/unit/test_app.py
- tests/unit/test_metrics.py
> Fix #461: Add `/acoustic_configuration` endpoint to expose Acoustic fields configuration

- ctms/backport_legacy_waitlists.py
- tests/unit/test_api_patch.py
> Ref #469: Unsubscribe from `vpn` waitlist when unsubscribing from `guardian-vpn-waitlist` newsletter

- ctms/bin/client_credentials.py
- ctms/crud.py
- ctms/ingest_stripe.py
- ctms/schemas/mofo.py
- tests/unit/test_acoustic_service.py
Apparently my usage of the "auto-merge" feature isn't appropriate (yet?).
See #537 , that was merged with failing `lint` CI test 🤷
> Run formatting black 23.1.0

- ctms/app.py
- ctms/log.py
- tests/unit/test_log.py
>  Fix #493: add request id to MozLog 

- ctms/bin/delete_bulk.py
- docs/deployment_guide.md
*  `gdpr` is a european law, prefer a generic name
* use the `.py` extension for consistency with other commands
> Rename the `gdpr` command to `delete_bulk.py`

- ctms/bin/acoustic.py
- ctms/crud.py
- tests/unit/test_bin_acoustic_resync.py
This comes on top of #569, only last commit should be reviewed :)
> Ref #565: Reset `retry` status from `acoustic.py resync` command

- .github/workflows/dependabot-automerge.yaml
> Add Dependabot automation workflow

- ctms/bin/acoustic.py
https://github.com/mozilla-it/ctms-api/pull/686#discussion_r1231108680
> Ref #686: follow-up, remove useless condition

- ctms/bin/acoustic.py
- tests/unit/bin/test_acoustic.py
> Fix #709: use two passes to produce CSV dump

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
- ctms/monitor.py
- ctms/routers/platform.py
- docs/README.md
- docs/developer_setup.md
- docs/testing_strategy.md
- `repo-standard-files`
- `repo-readme-sections`
- `monitoring-heartbeat-error`
- `documentation-test-args`
> Ref #681: Improve quality standards

- docs/diagrams/bedrock_basket_ctms_acoustic.md
- tests/integration/test_basket_waitlist_subscription.py
> Fix #605: Adjust Basket integration test and workflow docs

- .secrets.baseline
- ctms/acoustic_service.py
- tests/unit/test_acoustic_service.py
> Fix #761: fix waitlist boolean data type

- ctms/acoustic_service.py
- tests/unit/test_acoustic_service.py
https://mozilla.sentry.io/issues/4338708158/?referrer=slack&alert_rule_id=13795152&alert_type=issue
> Follow-up #562: fix bool column conversion

- ctms/log.py
This is partially related to #771 and also a [recommendation of Dockerflow](https://github.com/mozilla-services/Dockerflow/#optional-recommendations)
> Send StreamHandler loggers to stdout

- .env.example
- .github/workflows/ci.yaml
- .secrets.baseline
- Makefile
- bin/integration-test.sh
- bin/test.sh
- docker-compose.yaml
- docs/configuration.md
- docs/developer_setup.md
See: https://github.com/actions/runner-images/issues/9692
> Switch `docker-compose` to `docker compose`
