mozilla-it/ctms-api

.secrets.baseline

With ignored files applied, there are no detected secrets. My upcoming changes _will_ add a secret, so I wanted a clean baseline before it was added.
To update the file, I ran:
```
poetry shell
detect-secrets scan --update .secrets.baseline --exclude-files poetry.lock
```

Clear .secrets.baseline

---

poetry.lock

I'm about to add some new packages, which tends to update some related packages, so I wanted to update existing packages first. After running "poetry update", these packages are updated:
* alembic 1.5.5 to 1.5.6: bug fix, async preparations
* identify 2.0.0 to 2.1.1: identify sockets, build fixes
* importlib-metadata 3.7.0 to 3.7.2: New feature, refactoring
* pre-commit 2.10.1 to 2.11.0: Support post-merge hook, fixes
* pydantic 1.8 to 1.8.1: Bug fixes
* pygments 2.8.0 to 2.8.1: Add and update lexers, other features
* Sphinx 3.5.1 to 3.5.2: Bug fixes
* zipp 3.4.0 to 3.4.1: Refresh packaging
``make test`` and ``make start`` work locally for me.

Update alembic, other packages

---

docker/Dockerfile

Will be worked on in more depth in https://github.com/mozilla-it/ctms-api/issues/89
but, our helm chart exports port 8000 at the moment, and since that's where we are planning on ending up
making this quick change now.

Changing Dockerfile to listen on port 8000

---

pyproject.toml

To get migrations working in prod we need the prod container to have alembic
Rather than running a different container for migrating the db
moving the dependency to the prod container

Move alembic to prod container

---

.secrets.baseline
ctms/app.py
ctms/auth.py
ctms/bin/client_credentials.py
ctms/config.py
ctms/crud.py
ctms/models.py
ctms/schemas/__init__.py
ctms/schemas/api_client.py
ctms/schemas/web.py
docker/config/local_dev.env
guides/developer_setup.md
migrations/versions/20210309_435d9701a9a4_add_api_client_table.py
poetry.lock
pyproject.toml
tests/unit/conftest.py
tests/unit/test_api.py
tests/unit/test_app.py
tests/unit/test_auth.py
tests/unit/test_bin_client_credentials.py
tests/unit/test_private_api.py

To fix issue #57, add [OAuth2 authentication](https://tools.ietf.org/html/rfc6749) using [client credentials](https://oauth.net/2/grant-types/client-credentials/).
A new endpoint `/token` implements the OAuth2 client credentials grant process. A caller passes a ``client_id`` and a ``client_secret``, either in the form body or a header, and gets an OAuth2 token that expires. The token is implemented as a [JSON Web Token](https://en.wikipedia.org/wiki/JSON_Web_Token) or JWT, signed by the server (HMAC with SHA-256). When the token expires (default of 60 minutes), the client calls ``/token`` again.
All API endpoints now require a bearer token. The Swagger API docs already include a mechanism for authenticating in the browser.
There's a new database table ``api_client`` that stores the …

Add OAuth2 authentication (57)

---

ctms/crud.py
ctms/models.py
tests/unit/test_crud.py

To fix issue #51:
* Refactor the main query from ``get_contact_by_email_id`` and ``get_contacts_by_any_id`` into ``_contact_base_query``, and use some SQLAlchemy [relationship loading techniques](https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html) to load related data directly onto the ``Email`` object. This increases efficiency when multiple contacts are loaded for an alternate ID, changing from N+1 queries to 2, up to N=500 contacts.
* Return newsletters ordered by name, for consistent output.
* Add direct tests of CRUD methods, including a ``StatementWatcher`` for counting SQL queries and debugging issues.
Future work I talked myself out of for this round:
* Change ``get_contact_by_email_id`` to ``get_email_by_email_id``, and just return the ORM ``Email`` instance. This …

Refactor complete contact queries

---

ctms/app.py

Without this it yells
```
Argument "auto_error" to "HTTPBasic" has incompatible type "None"; expected "bool"mypy(error)
```
@jwhitlock, does this change make sense?

Fix mypy yelling about auto_error

---

.github/workflows/build-image.yaml
.secrets.baseline
Makefile
ctms/app.py
ctms/monitor.py
docker-compose.yaml
docker/Dockerfile
docker/config/env.dist
guides/deployment_guide.md
guides/developer_setup.md
guides/testing_strategy.md
tests/unit/test_app.py
version.json

For issue #89, adjust ``Dockerfile`` for [dockerflow](https://github.com/mozilla-services/dockerflow):
* Add an environment variable ``PORT``, default 8000, to control the port that the application is served from.
- This required changing to ``ENTRYPOINT ["/docker-entrypoint.sh"]``, so that ``CMD`` could use shell expansion to get the value of ``$PORT``
* Add a user ``app``, default to user id 10001 and group id 10001, give it ownership of the application files, and run the application as the ``app`` user.
- The ``app`` user can cause problems for Linux users, if it creates files owned by user 10001 that the development account can't read or delete. If this happens, there are ``.env`` overrides ``CTMS_UID`` and ``CTMS_GID`` to set these for local development.
* Add a generic …

Adopt Dockerflow, other changes

---

ctms/crud.py
tests/unit/test_api.py

Fix #50 by converting ``get_amo_by_email_id``, ``get_fxa_by_email_id``, and ``get_vpn_by_email_id`` from ``.first()`` to ``.one_or_none()``, to detect early if there are multiple records for one ``email_id``.
Convert ``get_newsletters_by_email_id`` from ``.first()`` to ``.all()``, which mostly affected how to test if none were written.
Remove ``get_email_by_email_id``, which was unused and untested.

Convert ``.first()`` to ``.one_or_none()`` or ``.all()

---

tests/unit/test_auth.py

The docker container is in UTC so the timestamps it generates are in
that timezone. The `datetime.utcnow()...timestamp()` in tests is kinda
funny. The note in
https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp
explains a bit more. Basically when I tried running pytest on my machine
(which is in PST currently), the result of that call was 7 hours in the
past instead of correctly in UTC.
Happy to be told this is wrong if I'm misundersanding something. I _think_ this
is right but timezones are hard!

Allow testing outside of docker

---

ctms/auth.py
tests/unit/test_auth.py

[datetime.utcnow()](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) returns the current UTC time as a naive datetime, which is often interpreted as a local time. The Python docs recommend using [datetime.now(timezone.utc)](https://docs.python.org/3/library/datetime.html#datetime.datetime.now) instead. I'm having a hard time thinking of when ``utcnow()`` is appropriate.
This is follow-on work for PR #110. It works with ``make test``. I don't have my environment setup to test outside of docker.
- Bugfix (non-breaking change which fixes an issue)
- ✓ I have read the [guides](https://github.com/mozilla-it/ctms-api/tree/main/guides)
- ✓ I have followed the [Mozilla Lean Data …

Convert utcnow() to now(utc)

---

.pre-commit-config.yaml
ctms/app.py
ctms/crud.py
ctms/models.py
ctms/schemas/__init__.py
ctms/schemas/contact.py
ctms/schemas/email.py
migrations/versions/20210319_3c94af7ca946_add_unique_constraint_to_newsletters.py
pyproject.toml
tests/unit/test_api.py

Should approximately finish #55 (although there are a few discrepancies to clear up now that I look) Maybe worth doing in a followup though

Contact PUT

---

ctms/app.py

Follow [SQLAlchemy's advice](https://docs.sqlalchemy.org/en/13/orm/contextual.html#using-thread-local-scope-with-web-applications) to use [scoped_session](https://docs.sqlalchemy.org/en/13/orm/contextual.htm) to wrap the session factory. This may be unnecessary with FastAPI's dependency injection, but if we're wrong, it should prevent issues of multiple threads getting the same (not thread-safe) session.
Fixes #70
- New feature (non-breaking change which adds functionality)
- ✓ I have read the [guides](https://github.com/mozilla-it/ctms-api/tree/main/guides)
- ✓ I have followed the [Mozilla Lean Data Policies](https://www.mozilla.org/en-US/about/policy/lean-data/)
- ✓ Lint and tests pass both locally and on the cicd with my changes
- N/A I …

Use scoped_session for database session

---

.github/workflows/test-build.yaml
.secrets.baseline
scripts/update_baseline.sh

Fix #114, running a PostgreSQL server so that tests will have a database.
This also required a change to ``scripts/update_baseline.sh``, since it was not scanning files past the second level, and should have been using a regex instead of a list.
- Bugfix (non-breaking change which fixes an issue)
- ✓ I have read the [guides](https://github.com/mozilla-it/ctms-api/tree/main/guides)
- ✓ I have followed the [Mozilla Lean Data Policies](https://www.mozilla.org/en-US/about/policy/lean-data/)
- ✓ Lint and tests pass both locally and on the cicd with my changes
- N/A I have added tests that prove my fix is effective or that my feature works
- N/A I have added necessary documentation (if appropriate)
- N/A Any dependent changes have been merged and …

Test pull requests

---

ctms/app.py
ctms/crud.py
ctms/schemas/__init__.py
ctms/schemas/contact.py
ctms/schemas/email.py
tests/unit/test_api.py
tests/unit/test_api_patch.py
tests/unit/test_crud.py

As part of issue #128, add a ``PATCH /ctms/{email_id}`` API.
* The request is similar to ``PUT /ctms/{email_id}``, but the object must already exist
* It can't be used to change the ``email_id``
* Only the included items are updated; excluded items keep the existing values
* If a group is set to all default values, it is deleted from the database
* Newsletter subscription can be done by adding it to the ``newsletters`` list. It is not required to send all the user's subscriptions, but Basket probably will anyway.
* Newsletter unsubscription is done by setting ``"subscribed": False`` for that subscription, ``name`` is required. 
Differences from issue #128:
* I used a ``303 See Other`` redirect instead of a ``200``. I think a 2xx response is still a good idea to work better with the …

Add PATCH /ctms/{email_id}

---

ctms/app.py
ctms/crud.py
ctms/schemas/contact.py
tests/unit/test_api_patch.py

To fix issue #131, add some more features to the ``PATCH`` API:
* If there is an ID collision, such as a matching ``primary_email``, return a ``409 Conflict`` and make none of the changes.
* Use ``{"newsletters": "UNSUBSCRIBE"}`` to unsubscribe from all newsletters
* Use ``{"amo": "DELETE"}`` to delete the CTMS add-ons data and reset to defaults. A similar command works for ``fxa``, ``mofo``, and ``vpn_waitlist``.
- ✓ Bugfix (non-breaking change which fixes an issue)
- ✓ New feature (non-breaking change which adds functionality)
- ✓ I have read the [guides](https://github.com/mozilla-it/ctms-api/tree/main/guides)
- ✓ I have followed the [Mozilla Lean Data Policies](https://www.mozilla.org/en-US/about/policy/lean-data/)
- ✓ Lint and tests …

Add more features to ``PATCH`` API

---

ctms/auth.py
tests/unit/test_auth.py

Allow ``grant=refresh-token`` as well as ``grant=client-credentials`` for the ``/token`` endpoint to get an access token. The ``client_id`` and ``client_password`` are still required, and a ``refresh_token`` is not provided, required or checked. This gives it the same security as granting the original token.
This fixes issue #132, which explains why Basket will use this code.

Add grant=refresh-token to /token

---

ctms/app.py
ctms/config.py
ctms/logging.py
docker/Dockerfile
docker/config/local_dev.env
docker/log_config.json
guides/configuration.md
guides/deployment_guide.md
guides/developer_setup.md
poetry.lock
pyproject.toml
tests/unit/test_logging.py

For issue #106, add the option (`CTMS_USE_MOZLOG=True`) to use the MozLog JSON format (see https://wiki.mozilla.org/Firefox/Services/Logging), for uvicorn request logging, as well as any other logs we would add. The log includes the details of the request, as well as some additional application context.
For testing, rebuild with ``make build`` and add to your ``.env`` file:
```
CTMS_USE_MOZLOG=True
```
then restart your development server, try out the interactive API
Here's a log line:
```json
{"Timestamp": 1618616777743526400, "Type": "uvicorn.access", "Logger": "ctms", "Hostname": "ad3f42667525", "EnvVersion": "2.0", "Severity": 6, "Pid": 207, "Fields": {"status_code": 200, "type": "http", "http_version": "1.1", "scheme": "http", "method": "GET", "root_path": "", "path": "/ctms", …
```

Add MozLog format for request logging

---

poetry.lock
pyproject.toml
scripts/lint.sh
tests/unit/conftest.py
tests/unit/test_api.py
tests/unit/test_app.py
tests/unit/test_auth.py
tests/unit/test_bin_client_credentials.py
tests/unit/test_crud.py
tests/unit/test_ingest.py

Add [pylint-pytest](https://github.com/reverbc/pylint-pytest), which tunes pylint to remove false positives around pytest fixtures and other conventions (and is completely different from [pytest-pylint](https://github.com/carsongee/pytest-pylint), which turns pylint issues into pytest errors).
Once the cruft is gone, almost all the issues were cosmetic (``sw`` for ``StatementWatcher`` changed to ``watcher``, remove some unused variables). There were a few linting issues that were bugs in the tests, such as looping through contacts but only testing the first contact.
My editor is configured to run pylint on every save, so the pylint errors in tests are annoying me, probably more than anyone else. This fixes linting of tests, and also adds tests to the linting commands. I'd be willing to …

Add pylint-pytest, and lint the tests

---

ctms/app.py
ctms/config.py
docker/Dockerfile
guides/configuration.md
poetry.lock
pyproject.toml

For issue #139:
* Add ``sentry-sdk``
* Initialize it from ``SENTRY_SDK`` and with the commit number from ``version.json``.
* Wrap the FastAPI app with the [ASGI middleware](https://docs.sentry.io/platforms/python/guides/asgi/). This is done in a new variable because the Sentry middleware doesn't expose the wrapped app's interface, and to make ``mypy`` happier.
* Use the wrapped Sentry app in dev and production
I've added a new setting ``CTMS_SENTRY_DEBUG`` to turn on debug-level logging for Sentry, which makes for a noisy initialization and shutdown.
To test it locally, I added these settings in `.env`:
```sh
CTMS_SENTRY_DEBUG=1
SENTRY_DSN=https://bad-9c7b6b6bcb7a45d7ae01fe8f60594083@sentry.127.0.0.1.nip.io/0
```
and then ran ``make test`` and ``make start``, and adding a line like …

Add Sentry middleware, rely on server-side filtering

---

ctms/app.py
ctms/bin/load_sample_csv.py
ctms/bin/prepare_csvs.py
ctms/bin/report_duplicates.py
ctms/bin/sync_bq_tables.py
ctms/crud.py
ctms/csv_helpers.py
ctms/ingest.py
ctms/schemas/contact.py
ctms/schemas/email.py
ctms/schemas/fxa.py
tests/unit/test_bin_load_sample_csv.py
tests/unit/test_ingest.py

Each of these changes is relatively self-contained in a commit.
- Allow configuring bq tables
- Stop modifying prod data as if it is test data
- Initial import followups
- Allow loading csvs in prod
- Give up on validating emails for now
- Make debugging imports a bit easier
- Handle duplicates in ingestion
- Move csv modifiers into helper
- Add scripts for modifying csvs
In particular, I'd say checking that the removal of EmailStr makes sense. Much of this is just dumping in semi-horrible scripts that I used to make the imports work. This is just for later use if we need them. I make no promises about them not being TODO-riddled junk.

Imports actually work now

---

.pre-commit-config.yaml
ctms/app.py

Sentry was interfering with the `pylint_pytest` plugin, and shouldn't be initialized in tests. By moving ``sentry_sdk.init`` inside of ``startup_event``, it is not initialized for tests, and the plugin works.
I've also adjusted the pre-commit hook to run linting on the tests.

Move Sentry initialization to app startup

---

ctms/app.py
docker/Dockerfile
tests/unit/test_app.py

For issue #139, adjust the Sentry integration strategy:
Move initialization to a function ``init_sentry()``. This reads ``sentry_debug`` from settings, which can fail if a required setting like the database URL is missing. This is what was causing the ``pylint-pytest`` plugin to fail for me earlier.
Call ``init_sentry()`` at the module level, unless it looks like we're running tests. It is needed at the module level because FastAPI integrates async and sync code by running sync code in thread pools, and Sentry needs to be initialized for each thread. We don't want it to run during tests however (at least not without mocked network calls), and report our tested exceptions to Sentry. I'm using ``pytest`` in the command to detect tests, which should work 90% of the time. Most developers will …

Sentry integration (again)

---

ctms/app.py

This reverts commit 60985aedffb8827d6057c8fadb5772401d568008 from PR #117, to address re-opened issue #70.
FastAPI shares threads between requests, which causes issues for ``scoped_session``'s per-thread sessions.
@imbstack and @bsieber-mozilla have been able to reproduce in ctms-stage by making many similar requests in parallel.

Revert "Use scoped_session for database session"

---

.pre-commit-config.yaml
ctms/auth.py
ctms/crud.py
mypy.ini
scripts/lint.sh

As part of increasing mypy strictness (issue #177), switch to ``mypy.ini``, which makes it easier to override settings for particular files, and to share the configuration between the pre-commit hook and the linting script.
Add the ``warn-return-any`` option, which warns when a type with ``Any`` is returned from a function that declares a non-``Any`` return type. The default for non-annotated functions is to return ``Any``, and this includes libraries where mypy can't see the annotations. For ``ctms/crud.py``, this exposed some issues with return types for functions that can return ``None``. For ``ctms/auth.py``, it mostly involved specifying the types for return values from library functions.

Add mypy.ini, enabled warn-return-any

---

ctms/app.py
ctms/config.py
ctms/crud.py
ctms/metrics.py
docker/Dockerfile
docker/docker-entrypoint.sh
docker/gunicorn_conf.py
mypy.ini
poetry.lock
pyproject.toml
tests/unit/conftest.py
tests/unit/test_auth.py
tests/unit/test_metrics.py

For issue #124, add Prometheus metrics to the API:
* New app-level variable ``METRICS_REGISTRY`` is initialized in each thread, like Sentry
* New app-level variable ``METRICS`` is initialized at app startup
* Metrics are emitted by the logging middleware as the response is returned:
- ``ctms_requests_total`` and ``_created``: A counter incremented for each request, with labels method, path_template, and status code (estimated cardinality 45)
- ``ctms_requests_duration_seconds_*``: A histogram of request times, with breakpoints at 10ms, 50m, 100ms, 500ms, 1s, 5s, and 10s, with labels method and path *and status_code_family like ``2xx`` and ``4xx``* (estimated cardinality ~276~ 310)
- ``ctms_api_requests_total`` and ``_created``: A counter incremented for each API request with valid …

Add Prometheus metrics to API

---

ctms/acoustic_service.py
tests/unit/test_acoustic_service.py

Logging of the background task is showing that the responses from the live-system are failing due to complex objects being passed.
This PR is to remove the UUID being sent to the api's and opt for strings.

Updating service and tests for less complex objects on request

---

ctms/app.py
ctms/sample_data.py
tests/unit/test_api.py
tests/unit/test_metrics.py
tests/unit/test_monitor.py

Allow HEAD as well as GET requests to :
/__heartbeat__
/__lb_heartbeat__

Adding HEAD for heartbeat api calls. Issue #165

---

ctms/bin/acoustic_sync.py
ctms/config.py
ctms/sync.py

```
CTMS_ACOUSTIC_SYNC_FEATURE_FLAG
CTMS_ACOUSTIC_INTEGRATION_FEATURE_FLAG
```
Both booleans, defaulted to False in the BackgroundSettings.
`CTMS_ACOUSTIC_SYNC_FEATURE_FLAG` allows for enabling (True) the background machinery to begin looping and pulling records, otherwise (False) the background machinery will not loop.  
`CTMS_ACOUSTIC_INTEGRATION_FEATURE_FLAG` allows for enabling (True) the records to be sent to acoustic, otherwise (False) records will be dropped from the database.
---
```
CTMS_ACOUSTIC_SYNC_FEATURE_FLAG=True
CTMS_ACOUSTIC_INTEGRATION_FEATURE_FLAG=True 
```
Is the expected end state, when we're pulling all records and syncing them into acoustic.
---
```
CTMS_ACOUSTIC_SYNC_FEATURE_FLAG=True
CTMS_ACOUSTIC_INTEGRATION_FEATURE_FLAG=False 
```
Is an interim state, when we're …

Adding FeatureFlags to the Sync Job as Background EnvVars

---

ctms/app.py
ctms/log.py
tests/unit/test_app.py
tests/unit/test_metrics.py
tests/unit/test_monitor.py

Move the tests for ``__heartbeat__`` and ``__lbheartbeat__`` from ``test_app.py`` into ``test_metrics.py``.
Add field ``"trivial": true`` for requests that we'd like to ignore when looking at logs:
* Requests to the root URL (redirected to ``/docs``)
* Amazon or New Relic requesting ``/__heartbeat__``
* Kubernetes requesting ``/__lbheartbeat__``
* Prometheus requesting ``/metrics``
This will allow us to write a Papertrail query that omits these noisy requests for issue #153, such as:
```
ctms-api-stage program:ctms -"\"trivial\": true"
```

Add "trivial": true to logs for bots and boring requests

---

ctms/metrics.py
tests/unit/test_metrics.py

Add some test functions like ``assert_request_metric_inc``. This reduces the lines of code in the test functions themselves, making it a bit clearer what metrics are being tested. It also makes it a one-line test change for the metric change.
Add ``status_code_family`` label, like ``2xx`` and ``4xx`` to the ``ctms_requests_total`` metric. This already has ``status_code`` as a label, so the new label does not increase the cardinality. This will help when cross-referencing
against the Application Load Balancer (ALB) metrics, or when comparing success / failure ratios.
This is the last item for issue #124, adding metrics to the web app.

Add status_code_family to request web metric

---

ctms/app.py
ctms/schemas/__init__.py
ctms/schemas/bulk.py
tests/unit/test_api.py
tests/unit/test_bulk.py

On query params, a new validation error of 422 will be presented to users hitting the endpoint with any string.:
- empty string "" as an exception
- after is allowed to have strs, decoding is wrapped to throw a 422 if after is invalid.

Updating to 4xx on bad requests to bulk read

---

Makefile
docker-compose.lint.yaml

A potential solution for : https://github.com/mozilla-it/ctms-api/issues/66
adds:
`make lint`
_which rather checks to confirm/deny if linting has been done; rather than to lint the code._
---
💭 Should this be `lint-check`? 
💭 Would we want a `make lint` to lint the code as well? (Is this preferred to pre-commit?)
🤔

Adding a docker-compose lint check, that uses the dockerfile's multistage lint target

---

ctms/app.py
tests/unit/test_api_get.py
tests/unit/test_api_get_by_alt_id.py
tests/unit/test_api_patch.py
tests/unit/test_api_post.py
tests/unit/test_api_put.py

As suggested in issue #211, add a feature that traces requests if contact's primary email has the string ``+trace-me-mozilla-``, such as ``test+trace-me-mozilla-1@example.com``. The contact itself is examined, so the string does not need to appear in the request body.
Tracing is enabled for these API endpoints:
* ``GET /ctms``
* ``POST /ctms``
* ``GET /ctms/{email_id}``
* ``PUT /ctms/{email_id}``
* ``PATCH /ctms/{email_id}``
When active, two items are added to the log:
* ``trace={email}``, placing the email in the log. For ``GET /ctms``, if multiple emails are traced, the value is a comma-separated list of the traced emails
* ``trace_json={request_json}``, when the request has a JSON body (``POST``, ``PUT``, ``PATCH``)
The purpose is to allow debugging requests from an integrated service, …

Add log tracing for emails with "+trace-me-mozilla-"

---

ctms/app.py
ctms/metrics.py
tests/unit/test_metrics.py

For each process, use a separate ``CollectorRegistry`` initialized at startup.
For the ``/metrics`` view, use this collecter in single-process mode, but use a fresh ``CollectorRegistry`` with 
``MultiProcessCollector`` in multiprocess under ``gunicorn``. This should avoid duplicate metric exports (one for multiprocess, one for the process serving the request).
This was based off of reading [starlette_explorer](https://github.com/stephenhillier/starlette_exporter)'s middleware and view, as well as finally understanding this line of the [multiprocessing docs](https://github.com/prometheus/client_python#multiprocess-mode-eg-gunicorn):
> It is a best practice to create this registry inside the context of a request to avoid metrics registering themselves to a collector used by a …

Setup multiprocessing metrics registry in ``/metrics`` endpoint

---

ctms/bin/acoustic_sync.py
ctms/config.py

Enhance logging for background job.
It seemed that logs were lacking visibility. I added basiclogging, and use of argument parser to allow this to be provided at runtime, but default to debug.
`log level given:  -- must be one of: critical | error | warn | warning | info | debug`

Enhancing logging with background job. Adding argument -log/--log to set log level. Default to debug for visibility into running job.

---

ctms/app.py
ctms/bin/acoustic_sync.py
ctms/exception_capture.py

Move ``init_sentry`` from ``app.py`` to new file ``exception_capture.py``, and call it during startup for ``acoustic_sync.py``.
I think this is enough for Sentry integration, and will process any uncaught exceptions. There's currently one exception handler:
https://github.com/mozilla-it/ctms-api/blob/9a38b4fdb3f0c48c0d6565f93a574de303b36fab/ctms/acoustic_service.py#L328-L331
The Sentry [logging integration](https://docs.sentry.io/platforms/python/guides/logging/) will capture the stack trace from ``logger.exception``.

Add init_sentry to acoustic_sync

---

ctms/crud.py
ctms/models.py
migrations/versions/20210520_37edf9c48404_adding_lower_indexes.py

Previous solution: Use @validator decorators to convert incoming values to lowercase, so they are lowercase in the DB.
New solution: Don't modify default or validation logic, just add comparators for LC comparison on DB

Initial commit for enabling case-insensitivity, calling 'lower()' on primary_email's.

---

ctms/models.py
migrations/versions/20210520_37edf9c48404_adding_lower_indexes.py

> alembic current reports cad3c933830b (head)
Since the prior migration failed and RB'd to the previous revision, this PR removes the uniqueness element to the func.lower(primary_email) index

Modifying migration

---

ctms/acoustic_service.py
tests/unit/test_acoustic_service.py

Related:
> To follow-up tomorrow: possibly none of the dates we're sending from C->A are in a format that Acoustic likes. We're sending YYYY-MM-DD but Acoustic might need MM/DD/YYYY (ref: https://help.goacoustic.com/hc/en-us/articles/360043349433-Work-with-database-fields)
> Should be a(nother) simple change to the C->A script
> ...https://mozilla.slack.com/archives/G01BEQJFWS3/p1624593115185800

Updating from ISO to MM/DD/YYYY

---

ctms/crud.py

Whenever we receive a `segment` that results in "other" reset the `segment_prefix` to ""

If 'other' reset segment-prefix to blank

---

.secrets.baseline
ctms/sync.py
docs/deployment_guide.md
docs/developer_setup.md
tests/unit/test_sync.py

I added a section to the development docs for updating dependencies, which took me too long to figure out.
The deployment docs now have these sections:
* Overview - deployment URLs and notable paths
* Deployment - updated with some of the details of automated deployments
* Logging - refreshed with current API logging and the 1.1.x background process logging
* Example - Recreated from production
* Logging Fields - Overview of structured logging format
* API Logging Fields - The fields that can appear in API request logs
* Acoustic Sync Process Logging Fields - The log types and fields from the background process
* Metrics - new section for emitted metrics
* API metrics
* Acoustic Sync Service Metrics
* Dashboards - new, links to Graphana
When writing the logging documentation, I noticed …

Rewrite and expand the deployment docs, etc.

---

ctms/app.py
docker/Dockerfile
poetry.lock
pyproject.toml

While debugging issue #340, I noticed changes in the error-capturing code in Starlette, included in 0.15.0. The latest FastAPI uses Starlette 0.15.0, and recommends a three-step upgrade process. Tests found an issue with the 0.68.2 to 0.69.0 transition, but otherwise this was a smooth update in the development environment.
Tests pass, but with a new, repeated warning:
```
=========================================================== warnings summary ============================================================
tests/unit/test_api.py: 160 warnings
tests/unit/test_api_get.py: 6 warnings
tests/unit/test_api_get_by_alt_id.py: 22 warnings
tests/unit/test_api_patch.py: 112 warnings
tests/unit/test_api_post.py: 119 warnings
tests/unit/test_api_put.py: 132 warnings
tests/unit/test_api_stripe.py: 19 …
```

Update to FastAPI 0.70.0, Starlette 0.16.0, and Python 3.9.9

---

ctms/app.py
ctms/crud.py
ctms/ingest_stripe.py
tests/unit/test_api_stripe.py
tests/unit/test_ingest_stripe.py

Changes for issue #340:
* Use ``SELECT ... FOR UPDATE``, to try to ensure one writer at a time updates a Stripe row. This is done in the generic ``_get_stripe()`` function, as well as when getting the IDs of subscription items and invoice line items, to detect deletions.
* Use ``filter().one_or_none()`` instead of ``.get()``, to avoid the identity map cache
* Catch ``IntegrityError`` and ``OperationalError`` (deadlocks and other issues), log the exception, and return a 409, instead of a 500.

Update stripe objects more carefully

---

ctms/app.py
ctms/crud.py
ctms/ingest_stripe.py
docs/deployment_guide.md
tests/unit/test_api_stripe.py
tests/unit/test_crud.py
tests/unit/test_ingest_stripe.py

This should fix issue #343, where PubSub is sending a new Stripe customer with the same FxA ID as an existing customer. This is seen on stage, and appears to be due to a bug or direct interaction with the Stripe console. We currently return a 409 Conflict to the FxA PubSub push request, which means it is tried again a few milliseconds later.  Because the FxA Firestore indexes customers by FxA ID, it handles conflicts by overwriting the existing customer. This PR changes the behavior to delete the existing customer (mirroring the overwrite in FxA Firestore) and then import the new customer.
The first part detects the conflicting FxA ID in the application (``ingest_stripe_customer``) rather than during the database commit. For new customers, an extra ``SELECT`` is executed to find matching …

Log Stripe ingest actions, and delete existing customer on FxA ID conflict

---

ctms/app.py
pyproject.toml

* Use ``SELECT ... FOR UPDATE`` to avoid (some) database conflicts
* Improve updating logic to avoid needless updates
* Database conflicts (``IntegrityError``s and deadlocks and others) are returned as ``409 Conflict`` instead of ``500 Server Error``
* Handle duplicate FxA IDs in Stripe customers by deleting the existing customer record (seen in stage)
* Add details of Stripe objects in the request logs
* Update lxml from 4.6.4 to 4.7.1

Release 1.1.2 - Improve /stripe_from_pubsub ingest

---

ctms/app.py
pyproject.toml
tests/unit/test_api_stripe.py

Handle the case where a new Stripe customer starts out deleted. The ingest is successful (doesn't raise `StripeIngestUnknownObjectError`), but no object is created and the object returned is `None`.
Fixes #350. Since this is a production issue, also preparing for next release.

Handle POST of new deleted customer

---

ctms/config.py

_Does/should the ACK time-limit in GCP need to be adjsuted too?_
(It's currently set to 20s)

Modifying engine params back to defaults from SQLAlchemy. 

---

ctms/crud.py
tests/unit/test_ingest_stripe.py

Modifying parameters used during the locking of rows.
https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.Query.with_for_update

Removing 'of' param in call to 'with_for_update'

---

ctms/crud.py
tests/unit/test_ingest_stripe.py

The addition of 'of' to the with_for_update, increased the drain-rate and enabled more messages to be processed.

Revert "Removing 'of' param in call to 'with_for_update'"

---

ctms/config.py
ctms/database.py

https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.pool_recycle
Adding this param to create_engine; with default of 5min.

Adding environment variable for sql_alchemy create_engine call pool_recycle: `db_pool_recycle_in_seconds`

---

ctms/ingest_stripe.py
tests/unit/test_ingest_stripe.py

This data should not change very often and we are locking multiple times causing the entire application to lock up.

chore(stripe): Set for_update to False on price query

---

ctms/ingest_stripe.py
tests/unit/test_crud.py
tests/unit/test_ingest_stripe.py

This is only to clear the pubsub queue we're seeing on staging.  This should be reverted when the issue is resolved.

Temporarily disable / comment out "For Update" in SQL queries

---

.github/workflows/test-build.yaml
ctms/bin/acoustic_fields.py

The way linting is done is different than what I'm used to, and find it confusing. 
This PR adds an explicit step in the pull-request workflow. 
But there could be another way to fix it, by figuring out why:
- all targets are built here https://github.com/mozilla-it/ctms-api/blob/f49c740f466b819ca54e6f348eee9e9eed152aa9/.github/workflows/build-image.yaml#L79
- only the production target is built here https://github.com/mozilla-it/ctms-api/blob/f49c740f466b819ca54e6f348eee9e9eed152aa9/.github/workflows/test-build.yaml#L29-L35
Other things could be re-arranged, but not in this PR, like for example:
- duplicated lint commands between `lint.sh` and `Dockerfile`
- `lint.sh` is not used anywhere
- a dedicated dockerflow file for lint?

Add step to check lint in pull requests

---

.gitignore
.secrets.baseline
docker/lint.sh

Follow up of #475 
Since Docker on my machine is insupportably painful (like right now I run `make lint` and I get some errors like `docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))` while I just want to LINT MY LOCAL FILES!!!)
I tried to run linting with:
```
poetry install
poetry shell
./docker/lint.sh
```
> which would be my preferred way for `make lint`, but out of scope here
There are errors about secrets. So I ran:
```
./scripts/update_baseline.sh
git add .secrets.baseline
```
But then about `isort` isn't happy about the formatting of imports/wrapping.
Which are fixed by specifying the config file (`profile = "black"`).
Why don't we have these errors when running `./docker/lint.sh` from …

Follow #475: update secrets baseline

---

tests/unit/test_crud.py
tests/unit/test_ingest_stripe.py

In this PR, we:
- Remove test assertions that check for how many queries happened during a function invocation
- Remove assertions about the textual content of SQL statements generated by the ORM
- Remove the `StatementWatcher` class that allowed us to track these things
These assertions have seemed to make tests brittle and test implementation details. 
If it _is_ important to verify either the number of queries that a particular function emits or the SQL content of those queries, we should find a way to incorporate that into the test suite in a way that doesn't require changing `assert watcher.count == n` for every test function.

Remove SQL assertions

---

.github/workflows/lint.yaml
.github/workflows/test-build.yaml
Dockerfile
ctms/app.py
ctms/ingest.py
ctms/sync.py
poetry.lock
pyproject.toml

This PR bumps the version of Python we use to run CTMS from `3.10.9` to `3.11.1`.
In order to complete the upgrade, we also had to:
- update `pylint`, and make some related changes
- re-add `uvicorn` so we pulled in `uvloop>=0.17`

Bump Python to 3.11.1

---

ctms/schemas/waitlist.py
tests/unit/test_schema_waitlist.py

Fix #545
In v1.9.1 https://github.com/mozilla-it/ctms-api/blob/c17ae6911a33a7760e86e0554a3ec5ffb2f9472a/ctms/schemas/vpn.py#L23-L31 the platform field did not have any min length.
This PR restores the original behaviour.

Fix #545: allow empty string in waitlist platform field

---

ctms/schemas/newsletter.py
tests/unit/test_schema_contact.py

Fix #507: relax source URL validation

---

ctms/schemas/contact.py
tests/unit/conftest.py
tests/unit/sample_data.py
tests/unit/test_api_delete.py

Ref #548: make basket_token field optional in contact responses body

---

tests/unit/conftest.py

My tests were failing when running locally.
I tried several things at the DB level ([1](https://stackoverflow.com/a/51697579/141895), [2](https://github.com/Kinto/kinto/blob/af30f2d066d5b007bfac15510843b93e66e7c8cf/docs/community.rst#L127)), and apparently setting `TZ=UTC` in `bin/test.sh` for the client was not enough. 
This patch solves it for me, since it forces the timezone at connection... 🤷

Force UTC at SQLAlchemy client/session level

---

.secrets.baseline
Makefile
bin/lint.sh

`lint.sh` taken from https://github.com/mozilla/jira-bugzilla-integration/blob/main/bin/lint.sh

Add `make format` command

---

poetry.lock
pyproject.toml

Can't run the project with 3.11.2 otherwise

Do not enforce Python patch version

---

ctms/database.py
poetry.lock
pyproject.toml
tests/unit/conftest.py
tests/unit/factories.py
tests/unit/test_api_get.py
tests/unit/test_api_patch.py

We use [static data](https://github.com/mozilla-it/ctms-api/blob/main/tests/unit/sample_data.py) as test data throughout our tests. Some observations I've made about this data and the tests that use them:
- it makes test setup not obvious. I ask myself, "when a given test starts, what data is already present in the database?"
- they promote the use of ["magic numbers"](https://github.com/mozilla-it/ctms-api/search?q=%2267e52c77-950f-4f28-accb-bb3ea1a2c51a%22)
- they're used in [complex fixtures](https://github.com/mozilla-it/ctms-api/blob/23bf39231ab680a27f2518cee4f47186602fa28b/tests/unit/conftest.py#L244)
- The division between "minimal" and "maximal" contact seems arbitrary
In this PR, we would introduce the use of test factories with [Factory …

Start to use factories to generate test data

---

.secrets.baseline
tests/unit/conftest.py
tests/unit/sample_data.py
tests/unit/test_api_stripe.py
tests/unit/test_auth.py
tests/unit/test_crud.py
tests/unit/test_ingest_stripe.py

A follow-on of #628, in this PR, we move more data from `sample_data.py` to pytest fixtures in `conftest.py`, and use those fixtures in tests.
After this PR, there will be another that somehow moves `FAKE_STRIPE_ID` / `fake_stripe_id()` out of sample_data.py, then we can delete that module

Migrate `SAMPLE_STRIPE_DATA` to pytest fixtures

---

ctms/schemas/waitlist.py
tests/unit/test_api_get.py
tests/unit/test_schema_waitlist.py

Restore the behavior we had prior to #470

Fix #630: allow 'geo' field to be None or missing in waitlists

---

Makefile
ctms/backport_legacy_waitlists.py
ctms/schemas/contact.py
tests/integration/basket-db-init.sql
tests/integration/test_basket_waitlist_subscription.py
tests/unit/test_api_patch.py

Adjusts some aspects of the integration tests so that they match the latest changes to basket.
There are still some issues with `to_vendor` (https://github.com/mozmeao/basket/issues/1012), so we'll need to add more test cases here when that's figured out so we can capture regressions.

Adjust integration tests to Basket changes, fix bugs

---

tests/data/__init__.py
tests/factories/__init__.py
tests/factories/models.py
tests/factories/stripe.py
tests/unit/conftest.py
tests/unit/test_api_stripe.py
tests/unit/test_auth.py
tests/unit/test_crud.py
tests/unit/test_ingest_stripe.py

Ref: #633 
Deletes these fixtures:
- `stripe_customer_data`
- `raw_stripe_customer_data`
- `contact_with_stripe_customer`
In favor of factory usage in tests

Create Stripe customer factories, use in tests

---

ctms/bin/acoustic.py
ctms/crud.py
tests/unit/test_bin_acoustic_resync.py

With the previous code, the SQL query was `UPDATE pending_records SET id=X, retry=0`, without `WHERE` close. Leading to an integrity error when more than 1 pending record was updated.

Fix #647: fix bulk update for pending records

---

ctms/app.py
ctms/schemas/contact.py
tests/unit/test_api_patch.py

This PR adds `pydantic` `@validator` methods to provide defaults when initializing CTMSResponse models, instead of doing it inline.
It also uses a `root_validator` to initialize the legacy VPN waitlist fields. I don't necessarily prefer that method over using `__init__`, but it does feel like more of a standard pydantic pattern.

Use validators for `CTMSResponse` intialization

---

ctms/app.py
ctms/crud.py
ctms/sync.py
tests/unit/conftest.py
tests/unit/test_crud.py

This PR tweaks the way we query for contacts by `email_id` or my multiple IDs. Now, `get_contacts_by_email_id` returns a `Contact` object directly, and we combine the various functions we had to query multiple contacts into one `get_contacts_by_any_id` function.

Remove indirection in getting contacts

---

.secrets.baseline
tests/factories/models.py
tests/unit/conftest.py
tests/unit/test_acoustic_service.py
tests/unit/test_crud.py
tests/unit/test_ingest_stripe.py

Ref: #633
This PR creates factories for Stripe Subscription (model) objects and uses them in place of the `contact_with_stripe_subscription`. 
Follow-on PRs will:
- add Stripe Invoice-related model factories
- add Stripe REST object factories

Add Stripe Subscription model factories, start to use in tests

---

tests/factories/models.py
tests/unit/conftest.py
tests/unit/test_crud.py
tests/unit/test_ingest_stripe.py

Adds factories for `StripeInvoice` and `StripeInvoiceLineItem`, and starts to use them in tests.
The next PR in this series will modify some of the tests in `test_ingest_stripe`.
Addresses #633

Add fixture factories for `StripeInvoice` and `StripeInvoiceLineItem`

---

.github/dependabot.yml

We moved Dockerfiles to the root directory in b037a13, so we're updating the Dependabot config accordingly

Configure Dependabot to check root dir for Docker

---

bin/integration-test.sh
docker-compose.yaml

Our integration tests started to fail 6 days ago.
mariadb v11 was released and we were using `:latest`. Pinning to v10 fixes the tests.
The upgrade notes don't seem to mention anything relevant https://mariadb.com/kb/en/upgrading-from-mariadb-10-11-to-mariadb-11-0/
But here it is mentionned that official images don't have the `mysql` alias anymore...
https://mariadb.com/kb/en/mariadb-11-0-1-release-notes/#docker-official-images

Migrate integration tests to MariaDB v11

---

ctms/bin/acoustic.py
ctms/crud.py

Ref #565
Ref https://mozilla-hub.atlassian.net/browse/CTMS-146
Our plan would be to use to command to export certain sets of contacts as CSV and re-upload them to Acoustic to make sure they are up-to-date.
For example:
```
$ poetry run ctms/bin/acoustic.py dump --query="SELECT DISTINCT email_id FROM newsletters nl WHERE subscribed IS FALSE;"
Dump CSV for 623946 contacts [y/N]?
```

Ref #565: export contacts database as CSV

---

Makefile
bin/test.sh

Move all logic required for running the test suite into the `bin/test.sh` script so that we have more flexibility for how we run the tests.
We can still run `make test`, which will run all of the tests and produce a coverage report like before. But now, we can _also_ run `bin/test.sh` to optionally enable the coverage report and supply `pytest` args for more flexibility in how we run the test suite for local development, e.g. `bin/test.sh -k "test_module"`

Allow for more testing flexibility for local dev

---

tests/factories/models.py
tests/unit/conftest.py
tests/unit/test_crud.py

This PR:
- Adds a new `PendingAcousticRecord` factory
- refactors existing Acoustic-realted crud tests
- uses the new factory
- separates them so they're less "integration" and more "unit"

Refactor Acoustic crud tests

---

docker-compose.yaml

In https://github.com/mozmeao/basket/pull/1069 Basket tasks were transitionned to rq
This pins Basket to its previous version until we figure out how to migrate our integration test setup.

Pin Basket to 2023-04-24

---

migrations/versions/20230629_5bfd08b53489_create_update_timestamp_mixin.py

Merging #707 after #723 led to multiple alembic heads. This fixes it.

Fix database migration history

---

.secrets.baseline
docs/developer_setup.md

The docs should be focused on the specificities of the project, and not duplicate the docs of the different tools that we use.

Slim down developer docs

---

ctms/acoustic_service.py
tests/unit/test_acoustic_service.py

This is a drive-by that I found out while working on #762
There were two contradictory code comments. 
From what I understand in the docs, the queries don't take the time part into account, but timestamps can be stored.
https://help.goacoustic.com/hc/en-us/articles/360043347833-Queries-and-time-stamp-fields
```
Timestamp | Allows date and time in format mm/dd/yyyy hh:mm:ss
```
**Update**
Trying to store a date in timestamp column fails actually:
https://mozilla.sentry.io/issues/4320526677/?referrer=slack&alert_rule_id=13795152&alert_type=issue
So this becomes a bug fix.

Use timestamps instead of dates in Acoustic records

---

ctms/app.py
ctms/bin/acoustic_sync.py
ctms/log.py
ctms/routers/platform.py
docs/deployment_guide.md
tests/unit/bin/test_acoustic_sync.py
tests/unit/routers/test_platform.py

in PR #210, we introduced the notion of "trivial" requests to allow us to more-quickly filter logs in Papertrail for logs that actually mattered. This was partially due to the fact that Papertrail had poor filtering capabilities.
Now, since we're using a better logging platform, we can remove this "trivial" flag for logs and use Google Cloud's superior filtering capabilities to do our filtering.

Remove notion of `trivial` logs

---

ctms/acoustic_service.py
tests/unit/test_acoustic_service.py

Fix #778: switch newsletters timestamps columns to date and time

---

ctms/acoustic_service.py
tests/unit/test_acoustic_service.py

In #804 we fixed the way boolean fields are synced on the main table. This PR is a complementary specification about the way boolean related to FxA and AMO are synced.

Fix #802: clarify sync behaviour of boolean fields for relations 

---

ctms/acoustic_service.py
tests/unit/test_acoustic_service.py

The regression introduced in https://github.com/mozilla-it/ctms-api/commit/4ee09507cc461bcf5e4538dd167203a8ac8fe43d was not spotted because no unit test was asserting the output format of the `create_timestamp` format.
Also, Acoustic was ignoring silently the value sent in the `create_timestamp` column instead of rejecting the row. 
Note that we could have expected that sending `"05/21/2021 16:39:02"` for a `Date` field would have been ok...

Fix #812: fix Acoustic create_timestamp column

---

ctms/backport_legacy_waitlists.py
tests/unit/test_metrics.py

Since Basket will pull the data before sending a patch or put ([source](https://github.com/mozmeao/basket/blob/7443f8d71e9f49be34deb803acec7bd3d728dfd8/basket/news/tasks.py#L412-L418)), and since the get response contains the legacy waitlists fields (read-only), the counter does not represent well the amount of real legacy put/patch of waitlists attributes. 
This PR makes sure we only send the metric when only legacy attributes are sent. 
This is not fully ideal, since clients may send both attributes (`waitlists`, and `relay_waitlist`/`vpn_waitlist`) and still expect that the legacy will be taken into account (which [is not the case](https://github.com/mozilla-it/ctms-api/blob/2d313c90b7da31ac0d1b28a28f7e7f1aaca73555/ctms/backport_legacy_waitlists.py#L20)) but this is the decision we …

Ref #492, do not send legacy metric if new `waitlists` attribute is used

---

ctms/schemas/contact.py
ctms/schemas/newsletter.py
ctms/schemas/waitlist.py
tests/conftest.py
tests/integration/test_basket_waitlist_subscription.py
tests/unit/routers/contacts/test_api_get.py
tests/unit/routers/contacts/test_api_patch.py
tests/unit/routers/contacts/test_bulk.py

I'm not a big fan for those `del actual["create_timestamp"]` in the tests.
We could either have a `omit(dict, keys="")` util, or, better IMO, we could have a test util to fuzzy match values instead of actual timestamp values.
For example:
https://github.com/mozilla/normandy/blob/8ec2b525493ee0af7da3e8beee4be4f1669f740c/normandy/base/tests/__init__.py#L12-L51
```py
assert serializer.data == {
"signature": Whatever.regex(r"[a-f0-9]{40}"),
"x5u": Whatever.startswith(signature.x5u),
"timestamp": Whatever.iso8601(),
"public_key": Whatever.regex(r"[a-zA-Z0-9/+]{160}"),
}
```
https://github.com/mozilla/normandy/blob/8ec2b525493ee0af7da3e8beee4be4f1669f740c/normandy/recipes/tests/api/v1/test_serializers.py#L140-L145

Fix #814: add timestamps to newsletters and waitlists in contact responses

---

ctms/exception_capture.py

Fix #840: use version number in Sentry environment

---

ctms/auth.py
poetry.lock
pyproject.toml
tests/unit/conftest.py
tests/unit/routers/contacts/test_api_post.py
tests/unit/routers/contacts/test_api_put.py
tests/unit/test_auth.py
tests/unit/test_log.py

Bump FastAPI from `0.84.0 -> 0.108.0`
Bump Starlette from `0.19.1 -> 0.32.0`
Add `httpx` to dev dependencies to use FastAPI's `TestClient`. Also makes some related changes to how the client `PUT`s and `POST`s data

Bump `FastAPI` and `Starlette`, add `httpx`

---

suppression-list/README.md
suppression-list/csv2optout.py
suppression-list/example.csv

Turn suppression list CSV into a set of SQL files to be ran on the server 

---

ctms/config.py
ctms/routers/contacts.py
docs/deployment_guide.md
tests/unit/routers/contacts/test_api_get.py
tests/unit/routers/contacts/test_api_get_by_alt_id.py
tests/unit/routers/contacts/test_api_patch.py
tests/unit/routers/contacts/test_api_post.py
tests/unit/routers/contacts/test_api_put.py

Similar in spirit to https://github.com/mozilla-it/ctms-api/pull/770, I believe now that we have superior logging capabilities through GCP, we can safely remove this email tracing feature.

Remove `trace` feature for logs

---

ctms/crud.py

This avoids a very expensive COUNT query which could bog down the database

Update fallback health check query
